// Quick reference: what can be claimed, grouped. Item names only; the rates and percentages live with the accountant.
export const EXPENSES = [
  { group: "Nimo Solutions (company)", sections: [
    { title: "Software and online services", items: [
      "AI tools (Claude, ChatGPT, Cursor)",
      "Design tools (Figma, Framer, Lottielab, Mobbin, Adobe, Webflow)",
      "Dev and hosting (Vercel, Alchemy, AWS, GitHub, databases, APIs)",
      "Productivity (Notion, Linear, Slack, Google Workspace, Zoom, Calendly, Loom)",
      "Domains",
      "Stock assets, fonts, icons, templates, plugins",
      "Password manager, VPN, cloud storage",
      "Developer accounts (Apple, Google Play, Steam)",
      "Bookkeeping and payroll software (Xero, MYOB)",
      "Summ / crypto tax software",
    ] },
    { title: "Equipment and tech", items: [
      "Laptop, phone, tablet",
      "Monitors, keyboard, mouse, dock, cables, chargers, hard drives",
      "Headphones, webcam, mic, lighting",
      "Test devices for UI and app testing",
      "Prototype hardware and electronics",
      "Hardware wallets (Ledger, Trezor)",
      "Repairs to work equipment",
      "Insurance on business equipment",
    ] },
    { title: "Home and office", items: [
      "Desk, chair, standing desk, shelving",
      "Office decor, whiteboards, storage",
      "Air purifier, heater or fan for the office",
      "Coworking desk or day passes",
      "Stationery and office supplies",
      "Postage and couriers",
      "Business phone number, second SIM, travel eSIM",
    ] },
    { title: "Crypto", items: [
      "Gas and transaction fees",
      "Exchange, on-ramp and off-ramp fees",
      "Node, RPC and validator infrastructure",
      "Crypto data and news (Messari, Nansen, Dune)",
      "Foreign exchange losses on USD payments",
      "Capital losses, including lost or stolen crypto",
    ] },
    { title: "Product development", items: [
      "In-house software development (Propia, GoTendr tools)",
      "User testing, research tools, participant incentives",
      "Game engine assets and plugins",
      "Trademarks and IP registration",
      "R&D Tax Incentive (eligible R&D spend over $20k)",
    ] },
    { title: "Professional and admin", items: [
      "Accountant, tax agent, BAS preparation",
      "Legal (contracts, IP, structuring)",
      "ASIC annual fee, business name fees",
      "Bank, merchant, Stripe and PayPal fees",
      "Professional indemnity and public liability insurance",
      "Business set-up costs",
      "Interest on business loans or credit cards",
      "Debt collection costs",
      "Bad debts written off",
    ] },
    { title: "People", items: [
      "Contractors and freelancers",
      "Bookkeeper or virtual assistant",
      "Your wages through payroll",
      "Paris's wages for genuine work",
      "Super, including carry-forward unused caps",
      "Workers comp",
      "Recruitment and Upwork / Fiverr fees",
    ] },
    { title: "Marketing and growth", items: [
      "Ads (Google, Meta, LinkedIn)",
      "Website, SEO tools",
      "Business cards, printing, merch",
      "Video and photography",
      "LinkedIn Premium, directory listings",
    ] },
    { title: "Learning", items: [
      "Courses, bootcamps, certifications",
      "Books, newsletters, paid Substacks",
      "Conference and event tickets",
      "Industry memberships",
    ] },
    { title: "Travel and transport", items: [
      "Car trips to clients and sites (not commuting)",
      "Parking and tolls on business trips",
      "Uber / Grab to meetings and events",
      "Flights and accommodation for business trips",
      "Event-day transport",
    ] },
  ] },
  { group: "Personal return", sections: [
    { title: "Home and work", items: [
      "Working from home (electricity, gas, internet, phone)",
      "Home office furniture and equipment you paid for",
      "Cleaning a dedicated home office",
      "Car trips to clients and sites (if the company didn't reimburse)",
      "Shuffle work expenses not reimbursed",
    ] },
    { title: "Insurance, super and fees", items: [
      "Income protection insurance (outside super)",
      "Personal super contributions (lodge a notice of intent)",
      "Tax agent fees for your personal return",
    ] },
    { title: "Other", items: [
      "Donations to registered charities ($2+)",
      "Crypto capital losses",
    ] },
  ] },
];
